
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - shortener-network
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - shortener-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongodb
    networks:
      - shortener-network
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:password@mongodb:27017/url_shortener?authSource=admin
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    restart: always

networks:
  shortener-network:
    driver: bridge
